[package]
name = "miden-assembly"
version = "0.8.0"
description = "Miden VM assembly language"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
documentation = "https://docs.rs/miden-assembly/0.8.0"
categories = ["compilers", "no-std"]
keywords = ["assembler", "assembly", "language", "miden"]
edition = "2021"
rust-version = "1.73"

[lib]
bench = false
doctest = false

[features]
default = ["std"]
std = ["vm-core/std", "log/std"]

[dependencies]
log = { version = "0.4", default-features = false, optional = true }
num_enum = "0.7"
vm-core = { package = "miden-core", path = "../core", version = "0.8", default-features = false }
